### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by alexcanessa** [plantain-00/type-coverage#89] opened 2021-03-31 20:55 UTC
Hello,

I have a few users getting a `RangeError: Maximum call stack size exceeded` when running the `typescript-coverage-report` command, but (as you'll see from https://github.com/alexcanessa/typescript-coverage-report/issues/51#issuecomment-811443024) seems like the bug happens also when running `type-coverage` directly.

Anyone else?

**Comment by alexcanessa** [comment] 2021-06-07 10:05
@plantain-00 this seems to still be a bug (see the linked issue ^)

**Comment by Yonom** [comment] 2021-06-10 16:11
Also getting this error

Node: v16.3.0
TS: v4.2.2

**Comment by plantain-00** [comment] 2021-06-10 22:55
@Yonom  Can you provide a minimal repo to produce this?

**Comment by Yonom** [comment] 2021-06-11 01:08
Sure, I'll be busy tomorrow so it might take a day or two before I get around to it

**Comment by mateodelnorte** [comment] 2021-07-28 19:44
Also getting this.

**Comment by Yonom** [comment] 2021-07-29 12:04
I fixed the problem by deleting node_modules and installing everything again. Sadly I have been unable to reproduce the bug again

**Comment by robatwilliams** [comment] 2021-10-01 10:35
I have this when running directly too.

Windows 10
Node v14.15.5
"type-coverage": "2.18.2", - installed locally not globally
"typescript": "4.4.3",

The project is huge, and a mix of TS and JS. With `allowJs: false` it needs `--max-old-space-size` and completes successfully, however after turning on JS it needs `--max-old-space-size=24576` to avoid running out of heap - but then it exceeds max call stack size.

**Comment by robatwilliams** [comment] 2021-10-01 12:09
I found that `program.getSourceFiles()` is returning files from my `dist` directory, despite it not being in my tsconfig `include`. I expect that's a TypeScript issue.

Added `--ignore-files 'dist/**'` to workaround

**Comment by robatwilliams** [comment] 2021-10-01 15:57
When I enable the checker's strict mode, I'm back to max call size exceeded.

**Comment by Yonom** [comment] 2021-11-29 12:32
My issue was fixed by deleting node_modules and reinstalling everything. I haven't been able to reproduce it since

**Comment by albertogasparin** [comment] 2022-04-26 08:18
I'm also having this issue with a large codebase. I've tried to give 27 of my 32GB of RAM to the process but that is not enough 😞 
I wonder if the issue is with `sourceFileInfos` used to loop over and over across all files (we are talking about 50K+ files) and maintaining a massive map with source information.

Maybe changing the loop to be file by file instead of step by step would help node release the memory of processed files?

**Comment by plantain-00** [comment] 2022-04-26 10:30
> I'm also having this issue with a large codebase. I've tried to give 27 of my 32GB of RAM to the process but that is not enough 😞 I wonder if the issue is with `sourceFileInfos` used to loop over and over across all files (we are talking about 50K+ files) and maintaining a massive map with source information.
> 
> Maybe changing the loop to be file by file instead of step by step would help node release the memory of processed files?

`sourceFileInfos` just contains file path, sourceFile Reference, hash string: https://github.com/plantain-00/type-coverage/blob/58f7d2b94069fa742c59d2d6630e8fb1ab8b7319/packages/core/src/core.ts#L67-L72

It's file by file: https://github.com/plantain-00/type-coverage/blob/58f7d2b94069fa742c59d2d6630e8fb1ab8b7319/packages/core/src/core.ts#L38

My guess about the problem is checking every identifier's type: https://github.com/plantain-00/type-coverage/blob/58f7d2b94069fa742c59d2d6630e8fb1ab8b7319/packages/core/src/checker.ts#L38-L45

**Comment by albertogasparin** [comment] 2022-04-26 10:59
Maybe so, but is is a memory issue. It's not a problem of it being slow (yet), it feels like there is a memory leek or something as it keeps growing. So if the issue is there, it means that either `getTypeAtLocation` or `getContextualType` leak, otherwise I'd think `types` would be garbage collected. 
But I'm still just speculating as didn't have time to put a debugger and look at what is happening

**Comment by albertogasparin** [comment] 2022-04-27 03:00
Alright, had time to investigate a bit and found out the the issue is [with this fallback](https://github.com/plantain-00/type-coverage/blob/master/packages/core/src/tsconfig.ts#L145) as my tsconfig has neither `includes` nor `files`. So that generic wildcard `'**/*'` was matching things like `md`,`json`,`png`, `sh`, ... and I guess TS would choke trying to read some of them, never finishing the type check and eating all the memory.
By setting an explicit `includes: ['**/*.{ts,tsx}']` in my `tsconfig` then TS would handle 50K files just fine, and the program would perform decently.

Wonder if that is what is causing issues to other people here too and if we should make it a bit more specific.

**Comment by plantain-00** [comment] 2022-04-27 03:26
> Alright, had time to investigate a bit and found out the the issue is [with this fallback](https://github.com/plantain-00/type-coverage/blob/master/packages/core/src/tsconfig.ts#L145) as my tsconfig has neither `includes` nor `files`. So that generic wildcard `'**/*'` was matching things like `md`,`json`,`png`, `sh`, ... and I guess TS would choke trying to read some of them, never finishing the type check and eating all the memory. By setting an explicit `includes: ['**/*.{ts,tsx}']` in my `tsconfig` then TS would handle 50K files just fine, and the program would perform decently.
> 
> Wonder if that is what is causing issues to other people here too and if we should make it a bit more specific.

According to typescript document (https://www.typescriptlang.org/tsconfig#include ), if `files` is not specified, the default value of `include` is `**`
![屏幕快照 2022-04-27 11 24 15](https://user-images.githubusercontent.com/7639395/165433683-cca3554e-273e-486e-8bbe-e96b2c4f2ad7.png)
And typescript will support `.mts` and `cts`, so `**/*.{ts,tsx}` will break.

**Closed** 2022-11-21 15:21 UTC
Labels: bug, question
